// Generated by gfwlist2pac
// https://github.com/clowwindy/gfwlist2pac

var domains = __DOMAINS__;

var proxy = __PROXY__;

var direct = 'DIRECT;';

function FindProxyForURL(url, host) {
    var lastPos = 0;
    var domain = host;
    while(lastPos >= 0) {
        if (domains[domain]) {
            return proxy;
        }
        lastPos = host.indexOf('.', lastPos + 1);
        domain = host.slice(lastPos + 1);
    }
    return direct;
}
