/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -c DBusStartManager -p DBusStartManager com.deepin.StartManager.xml
 *
 * qdbusxml2cpp is Copyright (C) 2016 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#include "DBusStartManager.h"

/*
 * Implementation of interface class DBusStartManager
 */

DBusStartManager::DBusStartManager(const QString &service, const QString &path, const QDBusConnection &connection,
                                   QObject *parent)
        : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent) {
}

DBusStartManager::DBusStartManager(QObject *parent)
        : QDBusAbstractInterface("com.deepin.SessionManager", "/com/deepin/StartManager", staticInterfaceName(),
                                 QDBusConnection::sessionBus(), parent) {
    QDBusConnection::sessionBus().connect(this->service(), this->path(), "org.freedesktop.DBus.Properties",
                                          "PropertiesChanged", "sa{sv}as", this,
                                          SLOT(__propertyChanged__(QDBusMessage)));
}

DBusStartManager::~DBusStartManager() {
    QDBusConnection::sessionBus().disconnect(service(), path(), "org.freedesktop.DBus.Properties", "PropertiesChanged",
                                             "sa{sv}as", this, SLOT(propertyChanged(QDBusMessage)));
}
