Document: shadowsocks-deepin
Title: Debian shadowsocks-deepin Manual
Author: <insert document author here>
Abstract: This manual describes what shadowsocks-deepin is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/shadowsocks-deepin/shadowsocks-deepin.sgml.gz

Format: postscript
Files: /usr/share/doc/shadowsocks-deepin/shadowsocks-deepin.ps.gz

Format: text
Files: /usr/share/doc/shadowsocks-deepin/shadowsocks-deepin.text.gz

Format: HTML
Index: /usr/share/doc/shadowsocks-deepin/html/index.html
Files: /usr/share/doc/shadowsocks-deepin/html/*.html
