Document: shadowsocks-client
Title: Debian shadowsocks-client Manual
Author: <insert document author here>
Abstract: This manual describes what shadowsocks-client is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/shadowsocks-client/shadowsocks-client.sgml.gz

Format: postscript
Files: /usr/share/doc/shadowsocks-client/shadowsocks-client.ps.gz

Format: text
Files: /usr/share/doc/shadowsocks-client/shadowsocks-client.text.gz

Format: HTML
Index: /usr/share/doc/shadowsocks-client/html/index.html
Files: /usr/share/doc/shadowsocks-client/html/*.html
